# SPDX-License-Identifier: AGPL-3.0-or-later
# Modifications © 2026 Michael Maurizi Jr.

services:
  server:
    ports:
      - 3005:3005

  client:
    ports:
      - 3003:3003

  manage:
    volumes:
      - ./dev-data:/home/node/app/manage/dev-data
