# SPDX-License-Identifier: AGPL-3.0-or-later
# Modifications © 2026 Michael Maurizi Jr.

services:
  server:
    ports:
      - 3005:3005
      - 9229:9229
    command: start:debug

  client:
    ports:
      - 3003:3003
