import { Column, Entity, PrimaryGeneratedColumn, Unique } from "typeorm";

export enum VerificationType {
  FORGOT_PASSWORD = "forgot password",
  INITIAL = "initial"
}

@Entity()
@Unique(["email", "type"])
export class EmailVerification {
  // DSQL rejects SERIAL and integer IDENTITY; the squash migration declares
  // this as `bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1)`.
  @PrimaryGeneratedColumn({ type: "bigint" })
  id: string;
  @Column()
  email: string;
  @Column()
  emailToken: string;
  @Column()
  timestamp: Date;
  // DSQL has no enum types; stored as varchar with a CHECK constraint.
  @Column({ type: "varchar", length: 32 })
  type: VerificationType;
}
