// SPDX-License-Identifier: AGPL-3.0-or-later
// © 2026 Michael Maurizi Jr.

/* eslint-disable no-console, functional/no-loop-statements */
// Migration runner for DSQL.
//
// DSQL rejects TypeORM's default behavior in two ways:
//  1. TypeORM auto-creates the `migrations` tracking table with a `SERIAL`
//     integer primary key, which DSQL rejects. We pre-create it with a
//     `bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1)` column before
//     invoking the framework migration runner.
//  2. TypeORM wraps each migration's DDL + the INSERT into `migrations` in a
//     single transaction; DSQL rejects DDL+DML in one transaction. We set
//     `migrationsTransactionMode: "none"` on the DataSource to disable
//     per-migration transaction wrapping.
//
// Usage: `yarn migration:run` (delegates to this script via package.json).
import AppDataSource from "../data-source";

async function main() {
  const ds = AppDataSource;
  await ds.initialize();
  await ds.query(
    `CREATE TABLE IF NOT EXISTS "migrations" (
      "id" bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
      "timestamp" bigint NOT NULL,
      "name" varchar NOT NULL
    )`
  );

  const results = await ds.runMigrations({ transaction: "none" });
  if (results.length === 0) {
    console.log("No pending migrations.");
  } else {
    console.log(`Applied ${results.length} migrations:`);
    for (const r of results) console.log(`  ${r.name}`);
  }
  await ds.destroy();
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
