// Post-processes a TypeORM-generated migration file to make it DSQL-compatible.
//
// TypeORM's `migration:generate` diffs entities against a dev Postgres shadow
// database and emits standard Postgres DDL. Many of the patterns it emits are
// rejected by DSQL. This script rewrites the common ones automatically and
// prints warnings for patterns that need human judgment.
//
// Usage: `yarn migration:generate-dsql <path>` (wired via package.json).
// Or standalone: `ts-node transform-migration-for-dsql.ts <file>`.
//
// Constraints this script knows about (see project_dsql_constraints.md in the
// claude-code memory for the full list):
//
//   auto-rewrite          from                           to
//   --------------------  -----------------------------  ---------------------
//   uuid_generate_v4      uuid_generate_v4()             gen_random_uuid()
//   SERIAL PK             "id" SERIAL NOT NULL           "id" bigint IDENTITY
//   jsonb column type     "col" jsonb                    "col" text
//   json column type      "col" json                     "col" text
//   CREATE INDEX          CREATE INDEX                   CREATE INDEX ASYNC
//   UNIQUE INDEX          CREATE UNIQUE INDEX            CREATE UNIQUE INDEX ASYNC
//   sort order on index   ("col" DESC)                   ("col")
//   BIGSERIAL             "id" BIGSERIAL NOT NULL        "id" bigint IDENTITY
//
// Warnings only (human must fix):
//
//   - ALTER TABLE ADD COLUMN ... NOT NULL (even with DEFAULT)
//   - ALTER TABLE ALTER COLUMN ... SET NOT NULL
//   - FOREIGN KEY / REFERENCES
//   - CREATE TYPE ... AS ENUM
//   - Partial indexes (CREATE INDEX ... WHERE)
//   - Array column types (integer[], boolean array, etc.)
//   - CREATE EXTENSION

import { readFileSync, writeFileSync } from "fs";

type Transform = {
  readonly name: string;
  readonly pattern: RegExp;
  readonly replacement: string;
};

type Warning = {
  readonly name: string;
  readonly pattern: RegExp;
  readonly hint: string;
};

const AUTO_TRANSFORMS: readonly Transform[] = [
  {
    name: "uuid_generate_v4 → gen_random_uuid",
    pattern: /uuid_generate_v4\(\)/g,
    replacement: "gen_random_uuid()"
  },
  {
    name: "SERIAL → bigint IDENTITY",
    pattern: /"(\w+)" SERIAL NOT NULL/g,
    replacement: `"$1" bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) NOT NULL`
  },
  {
    name: "BIGSERIAL → bigint IDENTITY",
    pattern: /"(\w+)" BIGSERIAL NOT NULL/g,
    replacement: `"$1" bigint GENERATED BY DEFAULT AS IDENTITY (CACHE 1) NOT NULL`
  },
  {
    name: "jsonb → text",
    pattern: /\bjsonb\b/g,
    replacement: "text"
  },
  // json replacement has to come after jsonb and only match the bare type
  // keyword, not json_* function names.
  {
    name: "json → text (column type)",
    pattern: /" json([,) ])/g,
    replacement: '" text$1'
  },
  {
    name: "CREATE UNIQUE INDEX → CREATE UNIQUE INDEX ASYNC",
    pattern: /CREATE UNIQUE INDEX (?!ASYNC\b)/g,
    replacement: "CREATE UNIQUE INDEX ASYNC "
  },
  {
    name: "CREATE INDEX → CREATE INDEX ASYNC",
    pattern: /CREATE INDEX (?!ASYNC\b)/g,
    replacement: "CREATE INDEX ASYNC "
  },
  {
    name: "strip DESC/ASC from index columns",
    pattern: /("[\w]+")\s+(DESC|ASC)/g,
    replacement: "$1"
  }
];

const WARNINGS: readonly Warning[] = [
  {
    name: "ALTER TABLE ADD COLUMN ... NOT NULL",
    pattern: /ALTER TABLE [^`]*ADD "[^"]+"[^`,]*NOT NULL/g,
    hint: "DSQL rejects ADD COLUMN NOT NULL (even with DEFAULT). You cannot add a new NOT NULL column to an existing table. Options: (1) add the column as nullable and enforce NOT NULL at the app layer, or (2) include the column in the original CREATE TABLE (requires a new squash)."
  },
  {
    name: "ALTER COLUMN SET NOT NULL",
    pattern: /ALTER COLUMN "[^"]+" SET NOT NULL/g,
    hint: "DSQL rejects SET NOT NULL. NOT NULL must be declared at CREATE TABLE time."
  },
  {
    name: "FOREIGN KEY constraint",
    pattern: /FOREIGN KEY|REFERENCES /g,
    hint: "DSQL has no foreign keys. Drop the ADD CONSTRAINT statement; integrity becomes app-layer."
  },
  {
    name: "CREATE TYPE AS ENUM",
    pattern: /CREATE TYPE "[^"]+" AS ENUM/g,
    hint: "DSQL has no custom types. Replace the enum column with `varchar(N) CHECK (col IN ('...','...'))` in the original CREATE TABLE."
  },
  {
    name: "partial index (WHERE clause on CREATE INDEX)",
    pattern: /CREATE (UNIQUE )?INDEX[^`]*WHERE/g,
    hint: "DSQL doesn't support partial indexes. Either drop the WHERE or restructure so the filter columns are leading columns of a full index."
  },
  {
    name: "array column type",
    pattern: /"\w+" \w+ array|"\w+" \w+\[\]/g,
    hint: "DSQL doesn't support array column types. Use `text` + TypeORM `simple-json` column type instead (stores as JSON string, auto-serializes)."
  },
  {
    name: "CREATE EXTENSION",
    pattern: /CREATE EXTENSION/g,
    hint: "DSQL doesn't allow extension installs. Drop this statement; the built-ins (gen_random_uuid, json operators) cover most needs."
  }
];

// Extract each backtick-delimited template literal from the source, transform
// only the SQL inside, and splice it back. This keeps the script from rewriting
// TypeScript comments or string literals outside the query-runner calls.
function forEachSqlString(
  source: string,
  fn: (sql: string) => string
): string {
  let out = "";
  let i = 0;
  while (i < source.length) {
    const start = source.indexOf("`", i);
    if (start < 0) {
      out += source.slice(i);
      break;
    }
    out += source.slice(i, start) + "`";
    const end = source.indexOf("`", start + 1);
    if (end < 0) {
      out += source.slice(start + 1);
      break;
    }
    out += fn(source.slice(start + 1, end)) + "`";
    i = end + 1;
  }
  return out;
}

function transformMigration(source: string): {
  transformed: string;
  applied: readonly string[];
  warnings: readonly { name: string; hint: string; matches: number }[];
} {
  const appliedSet = new Set<string>();
  const warnings: { name: string; hint: string; matches: number }[] = [];

  const transformed = forEachSqlString(source, sql => {
    let current = sql;
    for (const t of AUTO_TRANSFORMS) {
      const before = current;
      current = current.replace(t.pattern, t.replacement);
      if (before !== current) appliedSet.add(t.name);
    }
    for (const w of WARNINGS) {
      const matches = current.match(w.pattern);
      if (matches && matches.length > 0) {
        const existing = warnings.find(x => x.name === w.name);
        if (existing) {
          warnings.push({
            name: w.name,
            hint: w.hint,
            matches: existing.matches + matches.length
          });
          warnings.splice(warnings.indexOf(existing), 1);
        } else {
          warnings.push({ name: w.name, hint: w.hint, matches: matches.length });
        }
      }
    }
    return current;
  });

  return {
    transformed,
    applied: Array.from(appliedSet),
    warnings
  };
}

function main(): void {
  const [, , file] = process.argv;
  if (!file) {
    console.error("usage: transform-migration-for-dsql <migration-file.ts>");
    process.exit(1);
  }
  const source = readFileSync(file, "utf-8");
  const { transformed, applied, warnings } = transformMigration(source);
  if (transformed !== source) {
    writeFileSync(file, transformed);
    console.log(`\nRewrote ${file} with ${applied.length} transforms:`);
    for (const a of applied) console.log(`  - ${a}`);
  } else {
    console.log(`\nNo auto-transforms applied to ${file}.`);
  }
  if (warnings.length > 0) {
    console.log(`\n${warnings.length} pattern(s) need human review:`);
    for (const w of warnings) {
      console.log(`\n  ⚠ ${w.name} (${w.matches} occurrence${w.matches === 1 ? "" : "s"})`);
      console.log(`    ${w.hint}`);
    }
    process.exit(2);
  }
  console.log("\nNo warnings. Migration looks DSQL-compatible.");
}

if (require.main === module) {
  main();
}

export { transformMigration };
