#!/bin/bash

set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
        "Usage: $(basename "$0")
Load all 51 state region configs for development purposes.

This loads region configs pointing to processed VEST election data
on S3 for all 50 states + DC, with 2016/2018/2020 voting data.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        # Bring up PostgreSQL
        docker compose \
            -f docker-compose.yml \
            up -d database

        # Wait for database to be ready
        echo "Waiting for database..."
        sleep 3

        # Upsert all 51 state region configs
        echo "Loading region configs..."
        docker compose \
            exec database psql -U districtbuilder districtbuilder -c "
              INSERT INTO region_config (name, country_code, region_code, s3_uri, version)
              VALUES
                ('Alabama', 'US', 'AL', 's3://districtbuilder-dev-238046523378/regions/US/AL/2026-03-30T01:10:39.000Z/', '2026-03-30T01:10:39.000Z'),
                ('Alaska', 'US', 'AK', 's3://districtbuilder-dev-238046523378/regions/US/AK/2026-03-30T03:07:16.000Z/', '2026-03-30T03:07:16.000Z'),
                ('Arizona', 'US', 'AZ', 's3://districtbuilder-dev-238046523378/regions/US/AZ/2026-03-30T01:44:39.000Z/', '2026-03-30T01:44:39.000Z'),
                ('Arkansas', 'US', 'AR', 's3://districtbuilder-dev-238046523378/regions/US/AR/2026-03-30T01:19:01.000Z/', '2026-03-30T01:19:01.000Z'),
                ('California', 'US', 'CA', 's3://districtbuilder-dev-238046523378/regions/US/CA/2026-03-30T15:27:27.608Z/', '2026-03-30T15:27:27.608Z'),
                ('Colorado', 'US', 'CO', 's3://districtbuilder-dev-238046523378/regions/US/CO/2026-03-30T15:18:20.443Z/', '2026-03-30T15:18:20.443Z'),
                ('Connecticut', 'US', 'CT', 's3://districtbuilder-dev-238046523378/regions/US/CT/2026-03-30T02:04:21.511Z/', '2026-03-30T02:04:21.511Z'),
                ('Delaware', 'US', 'DE', 's3://districtbuilder-dev-238046523378/regions/US/DE/2026-03-30T02:06:14.000Z/', '2026-03-30T02:06:14.000Z'),
                ('District of Columbia', 'US', 'DC', 's3://districtbuilder-dev-238046523378/regions/US/DC/2026-03-30T02:05:05.000Z/', '2026-03-30T02:05:05.000Z'),
                ('Florida', 'US', 'FL', 's3://districtbuilder-dev-238046523378/regions/US/FL/2026-03-30T15:21:37.457Z/', '2026-03-30T15:21:37.457Z'),
                ('Georgia', 'US', 'GA', 's3://districtbuilder-dev-238046523378/regions/US/GA/2026-03-30T02:28:44.316Z/', '2026-03-30T02:28:44.316Z'),
                ('Hawaii', 'US', 'HI', 's3://districtbuilder-dev-238046523378/regions/US/HI/2026-03-30T02:31:32.114Z/', '2026-03-30T02:31:32.114Z'),
                ('Idaho', 'US', 'ID', 's3://districtbuilder-dev-238046523378/regions/US/ID/2026-03-30T02:52:43.154Z/', '2026-03-30T02:52:43.154Z'),
                ('Illinois', 'US', 'IL', 's3://districtbuilder-dev-238046523378/regions/US/IL/2026-03-30T18:25:03.371Z/', '2026-03-30T18:25:03.371Z'),
                ('Indiana', 'US', 'IN', 's3://districtbuilder-dev-238046523378/regions/US/IN/2026-03-30T03:10:48.137Z/', '2026-03-30T03:10:48.137Z'),
                ('Iowa', 'US', 'IA', 's3://districtbuilder-dev-238046523378/regions/US/IA/2026-03-30T02:41:21.231Z/', '2026-03-30T02:41:21.231Z'),
                ('Kansas', 'US', 'KS', 's3://districtbuilder-dev-238046523378/regions/US/KS/2026-03-30T03:19:07.096Z/', '2026-03-30T03:19:07.096Z'),
                ('Kentucky', 'US', 'KY', 's3://districtbuilder-dev-238046523378/regions/US/KY/2026-03-30T03:20:07.380Z/', '2026-03-30T03:20:07.380Z'),
                ('Louisiana', 'US', 'LA', 's3://districtbuilder-dev-238046523378/regions/US/LA/2026-03-30T15:29:32.667Z/', '2026-03-30T15:29:32.667Z'),
                ('Maine', 'US', 'ME', 's3://districtbuilder-dev-238046523378/regions/US/ME/2026-03-30T03:30:13.775Z/', '2026-03-30T03:30:13.775Z'),
                ('Maryland', 'US', 'MD', 's3://districtbuilder-dev-238046523378/regions/US/MD/2026-03-30T03:29:03.641Z/', '2026-03-30T03:29:03.641Z'),
                ('Massachusetts', 'US', 'MA', 's3://districtbuilder-dev-238046523378/regions/US/MA/2026-03-30T15:26:14.171Z/', '2026-03-30T15:26:14.171Z'),
                ('Michigan', 'US', 'MI', 's3://districtbuilder-dev-238046523378/regions/US/MI/2026-03-30T15:35:37.378Z/', '2026-03-30T15:35:37.378Z'),
                ('Minnesota', 'US', 'MN', 's3://districtbuilder-dev-238046523378/regions/US/MN/2026-03-30T17:06:52.473Z/', '2026-03-30T17:06:52.473Z'),
                ('Mississippi', 'US', 'MS', 's3://districtbuilder-dev-238046523378/regions/US/MS/2026-03-30T03:47:45.120Z/', '2026-03-30T03:47:45.120Z'),
                ('Missouri', 'US', 'MO', 's3://districtbuilder-dev-238046523378/regions/US/MO/2026-03-30T17:45:31.810Z/', '2026-03-30T17:45:31.810Z'),
                ('Montana', 'US', 'MT', 's3://districtbuilder-dev-238046523378/regions/US/MT/2026-03-30T04:07:00.947Z/', '2026-03-30T04:07:00.947Z'),
                ('Nebraska', 'US', 'NE', 's3://districtbuilder-dev-238046523378/regions/US/NE/2026-03-30T04:16:25.365Z/', '2026-03-30T04:16:25.365Z'),
                ('Nevada', 'US', 'NV', 's3://districtbuilder-dev-238046523378/regions/US/NV/2026-03-30T16:32:10.106Z/', '2026-03-30T16:32:10.106Z'),
                ('New Hampshire', 'US', 'NH', 's3://districtbuilder-dev-238046523378/regions/US/NH/2026-03-30T04:11:21.440Z/', '2026-03-30T04:11:21.440Z'),
                ('New Jersey', 'US', 'NJ', 's3://districtbuilder-dev-238046523378/regions/US/NJ/2026-03-30T15:40:19.939Z/', '2026-03-30T15:40:19.939Z'),
                ('New Mexico', 'US', 'NM', 's3://districtbuilder-dev-238046523378/regions/US/NM/2026-03-30T04:25:29.929Z/', '2026-03-30T04:25:29.929Z'),
                ('New York', 'US', 'NY', 's3://districtbuilder-dev-238046523378/regions/US/NY/2026-03-30T18:31:09.401Z/', '2026-03-30T18:31:09.401Z'),
                ('North Carolina', 'US', 'NC', 's3://districtbuilder-dev-238046523378/regions/US/NC/2026-03-30T15:47:44.733Z/', '2026-03-30T15:47:44.733Z'),
                ('North Dakota', 'US', 'ND', 's3://districtbuilder-dev-238046523378/regions/US/ND/2026-03-30T04:08:15.714Z/', '2026-03-30T04:08:15.714Z'),
                ('Ohio', 'US', 'OH', 's3://districtbuilder-dev-238046523378/regions/US/OH/2026-03-30T04:40:42.192Z/', '2026-03-30T04:40:42.192Z'),
                ('Oklahoma', 'US', 'OK', 's3://districtbuilder-dev-238046523378/regions/US/OK/2026-03-30T04:42:15.316Z/', '2026-03-30T04:42:15.316Z'),
                ('Oregon', 'US', 'OR', 's3://districtbuilder-dev-238046523378/regions/US/OR/2026-03-30T15:52:10.582Z/', '2026-03-30T15:52:10.582Z'),
                ('Pennsylvania', 'US', 'PA', 's3://districtbuilder-dev-238046523378/regions/US/PA/2026-03-30T18:12:54.010Z/', '2026-03-30T18:12:54.010Z'),
                ('Rhode Island', 'US', 'RI', 's3://districtbuilder-dev-238046523378/regions/US/RI/2026-03-30T04:50:32.000Z/', '2026-03-30T04:50:32.000Z'),
                ('South Carolina', 'US', 'SC', 's3://districtbuilder-dev-238046523378/regions/US/SC/2026-03-30T05:00:20.566Z/', '2026-03-30T05:00:20.566Z'),
                ('South Dakota', 'US', 'SD', 's3://districtbuilder-dev-238046523378/regions/US/SD/2026-03-30T05:03:46.477Z/', '2026-03-30T05:03:46.477Z'),
                ('Tennessee', 'US', 'TN', 's3://districtbuilder-dev-238046523378/regions/US/TN/2026-03-30T16:00:02.511Z/', '2026-03-30T16:00:02.511Z'),
                ('Texas', 'US', 'TX', 's3://districtbuilder-dev-238046523378/regions/US/TX/2026-03-30T17:26:45.980Z/', '2026-03-30T17:26:45.980Z'),
                ('Utah', 'US', 'UT', 's3://districtbuilder-dev-238046523378/regions/US/UT/2026-03-30T16:06:08.469Z/', '2026-03-30T16:06:08.469Z'),
                ('Vermont', 'US', 'VT', 's3://districtbuilder-dev-238046523378/regions/US/VT/2026-03-30T16:08:34.169Z/', '2026-03-30T16:08:34.169Z'),
                ('Virginia', 'US', 'VA', 's3://districtbuilder-dev-238046523378/regions/US/VA/2026-03-30T16:10:17.197Z/', '2026-03-30T16:10:17.197Z'),
                ('Washington', 'US', 'WA', 's3://districtbuilder-dev-238046523378/regions/US/WA/2026-03-30T16:19:04.673Z/', '2026-03-30T16:19:04.673Z'),
                ('West Virginia', 'US', 'WV', 's3://districtbuilder-dev-238046523378/regions/US/WV/2026-03-30T16:19:57.935Z/', '2026-03-30T16:19:57.935Z'),
                ('Wisconsin', 'US', 'WI', 's3://districtbuilder-dev-238046523378/regions/US/WI/2026-03-30T16:22:09.229Z/', '2026-03-30T16:22:09.229Z'),
                ('Wyoming', 'US', 'WY', 's3://districtbuilder-dev-238046523378/regions/US/WY/2026-03-30T16:25:25.002Z/', '2026-03-30T16:25:25.002Z')
              ON CONFLICT (country_code, region_code) WHERE hidden <> true AND archived <> true DO UPDATE SET
                name = EXCLUDED.name,
                s3_uri = EXCLUDED.s3_uri,
                version = EXCLUDED.version;
            "

        echo "Loaded 51 region configs"

        # Load chambers for all states
        # Uses a helper script to generate chamber SQL from region_config IDs
        echo "Loading chambers..."
        docker compose \
            exec database psql -U districtbuilder districtbuilder -c "
              -- Delete existing chambers to avoid duplicates
              DELETE FROM chamber WHERE id NOT IN (SELECT DISTINCT chamber_id FROM project WHERE chamber_id IS NOT NULL)
                AND id NOT IN (SELECT DISTINCT chamber_id FROM project_template WHERE chamber_id IS NOT NULL);

              -- Insert US House + state legislature chambers for each state
              -- Using a CTE to look up region_config IDs by region_code
              WITH rc AS (
                SELECT id, region_code FROM region_config
                WHERE hidden = false AND archived = false
              )
              INSERT INTO chamber (name, number_of_districts, region_config_id)
              SELECT name, districts, rc.id FROM rc JOIN (VALUES
                -- US House of Representatives (2020 apportionment)
                ('AL', 'U.S. House', 7), ('AK', 'U.S. House', 1),
                ('AZ', 'U.S. House', 9), ('AR', 'U.S. House', 4),
                ('CA', 'U.S. House', 52), ('CO', 'U.S. House', 8),
                ('CT', 'U.S. House', 5), ('DE', 'U.S. House', 1),
                ('FL', 'U.S. House', 28), ('GA', 'U.S. House', 14),
                ('HI', 'U.S. House', 2), ('ID', 'U.S. House', 2),
                ('IL', 'U.S. House', 17), ('IN', 'U.S. House', 9),
                ('IA', 'U.S. House', 4), ('KS', 'U.S. House', 4),
                ('KY', 'U.S. House', 6), ('LA', 'U.S. House', 6),
                ('ME', 'U.S. House', 2), ('MD', 'U.S. House', 8),
                ('MA', 'U.S. House', 9), ('MI', 'U.S. House', 13),
                ('MN', 'U.S. House', 8), ('MS', 'U.S. House', 4),
                ('MO', 'U.S. House', 8), ('MT', 'U.S. House', 2),
                ('NE', 'U.S. House', 3), ('NV', 'U.S. House', 4),
                ('NH', 'U.S. House', 2), ('NJ', 'U.S. House', 12),
                ('NM', 'U.S. House', 3), ('NY', 'U.S. House', 26),
                ('NC', 'U.S. House', 14), ('ND', 'U.S. House', 1),
                ('OH', 'U.S. House', 15), ('OK', 'U.S. House', 5),
                ('OR', 'U.S. House', 6), ('PA', 'U.S. House', 17),
                ('RI', 'U.S. House', 2), ('SC', 'U.S. House', 7),
                ('SD', 'U.S. House', 1), ('TN', 'U.S. House', 9),
                ('TX', 'U.S. House', 38), ('UT', 'U.S. House', 4),
                ('VT', 'U.S. House', 1), ('VA', 'U.S. House', 11),
                ('WA', 'U.S. House', 10), ('WV', 'U.S. House', 2),
                ('WI', 'U.S. House', 8), ('WY', 'U.S. House', 1),

                -- State Senate / Upper Chamber
                ('AL', 'Senate', 35), ('AK', 'Senate', 20),
                ('AZ', 'Senate', 30), ('AR', 'Senate', 35),
                ('CA', 'State Senate', 40), ('CO', 'Senate', 35),
                ('CT', 'State Senate', 36), ('DE', 'Senate', 21),
                ('FL', 'Senate', 40), ('GA', 'State Senate', 56),
                ('HI', 'Senate', 25), ('ID', 'Senate', 35),
                ('IL', 'Senate', 59), ('IN', 'Senate', 50),
                ('IA', 'Senate', 50), ('KS', 'Senate', 40),
                ('KY', 'Senate', 38), ('LA', 'State Senate', 39),
                ('ME', 'Senate', 35), ('MD', 'Senate', 47),
                ('MA', 'Senate', 40), ('MI', 'Senate', 38),
                ('MN', 'Senate', 67), ('MS', 'State Senate', 52),
                ('MO', 'Senate', 34), ('MT', 'Senate', 50),
                ('NE', 'Legislature', 49), -- Unicameral
                ('NV', 'Senate', 21), ('NH', 'Senate', 24),
                ('NJ', 'Senate', 40), ('NM', 'Senate', 42),
                ('NY', 'State Senate', 63), ('NC', 'Senate', 50),
                ('ND', 'Senate', 47), ('OH', 'Senate', 33),
                ('OK', 'Senate', 48), ('OR', 'State Senate', 30),
                ('PA', 'State Senate', 50), ('RI', 'Senate', 38),
                ('SC', 'Senate', 46), ('SD', 'Senate', 35),
                ('TN', 'Senate', 33), ('TX', 'Senate', 31),
                ('UT', 'State Senate', 29), ('VA', 'Senate', 40),
                ('VT', 'Senate', 13), -- Multi-member: 30 seats across 13 districts
                ('WA', 'State Senate', 49), ('WV', 'Senate', 17), -- 34 seats, 2 per district
                ('WI', 'Senate', 33), ('WY', 'Senate', 31),

                -- State House / Lower Chamber (skip Nebraska - unicameral)
                ('AL', 'House of Representatives', 105),
                ('AK', 'House of Representatives', 40),
                ('AZ', 'House of Representatives', 30), -- 60 seats, 2 per district
                ('AR', 'House of Representatives', 100),
                ('CA', 'State Assembly', 80),
                ('CO', 'House of Representatives', 65),
                ('CT', 'House of Representatives', 151),
                ('DE', 'House of Representatives', 41),
                ('FL', 'House of Representatives', 120),
                ('GA', 'House of Representatives', 180),
                ('HI', 'House of Representatives', 51),
                ('ID', 'House of Representatives', 35), -- 70 seats, 2 per district
                ('IL', 'House of Representatives', 118),
                ('IN', 'House of Representatives', 100),
                ('IA', 'House of Representatives', 100),
                ('KS', 'House of Representatives', 125),
                ('KY', 'House of Representatives', 100),
                ('LA', 'House of Representatives', 105),
                ('ME', 'House of Representatives', 151),
                ('MD', 'House of Delegates', 47), -- 141 seats, 3 per district
                ('MA', 'House of Representatives', 160),
                ('MI', 'House of Representatives', 110),
                ('MN', 'House of Representatives', 134),
                ('MS', 'House of Representatives', 122),
                ('MO', 'House of Representatives', 163),
                ('MT', 'House of Representatives', 100),
                ('NV', 'Assembly', 42),
                ('NH', 'House of Representatives', 204), -- 400 seats, multi-member
                ('NJ', 'General Assembly', 40), -- 80 seats, 2 per district
                ('NM', 'House of Representatives', 70),
                ('NY', 'State Assembly', 150),
                ('NC', 'House of Representatives', 120),
                ('ND', 'House of Representatives', 47), -- 94 seats, 2 per district
                ('OH', 'House of Representatives', 99),
                ('OK', 'House of Representatives', 101),
                ('OR', 'House of Representatives', 60),
                ('PA', 'House of Representatives', 203),
                ('RI', 'House of Representatives', 75),
                ('SC', 'House of Representatives', 124),
                ('SD', 'House of Representatives', 35), -- 70 seats, 2 per district
                ('TN', 'House of Representatives', 99),
                ('TX', 'House of Representatives', 150),
                ('UT', 'House of Representatives', 75),
                ('VA', 'House of Delegates', 100),
                ('VT', 'House of Representatives', 104), -- 150 seats, multi-member
                ('WA', 'House of Representatives', 49), -- 98 seats, 2 per district
                ('WV', 'House of Delegates', 100),
                ('WI', 'State Assembly', 99),
                ('WY', 'House of Representatives', 62)
              ) AS c(code, name, districts) ON rc.region_code = c.code
              ON CONFLICT DO NOTHING;
            "

        # Set number_of_members for multi-member district chambers
        docker compose \
            exec database psql -U districtbuilder districtbuilder -c "
              -- Multi-member lower chambers (2 per district)
              UPDATE chamber SET number_of_members = array_fill(2, ARRAY[number_of_districts])
              WHERE name IN ('House of Representatives', 'House of Delegates', 'General Assembly', 'State Assembly')
                AND region_config_id IN (
                  SELECT id FROM region_config WHERE region_code IN ('AZ','ID','ND','NJ','SD','WA')
                  AND hidden = false AND archived = false
                );
              -- Maryland House of Delegates: 3 per district
              UPDATE chamber SET number_of_members = array_fill(3, ARRAY[number_of_districts])
              WHERE name = 'House of Delegates'
                AND region_config_id IN (
                  SELECT id FROM region_config WHERE region_code = 'MD'
                  AND hidden = false AND archived = false
                );
              -- West Virginia Senate: 2 per district
              UPDATE chamber SET number_of_members = array_fill(2, ARRAY[number_of_districts])
              WHERE name = 'Senate'
                AND region_config_id IN (
                  SELECT id FROM region_config WHERE region_code = 'WV'
                  AND hidden = false AND archived = false
                );
            "

        echo "Loaded chambers"
    fi
fi
