#!/bin/bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Modifications © 2026 Michael Maurizi Jr.

set -e

if [[ -n "${DB_DEBUG}" ]]; then
    set -x
fi

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    # chromium is only needed by backfill-thumbnails but cheap to keep idle.
    docker compose up -d database chromium
    docker compose run --no-deps --rm manage ./bin/run "$@"
fi
